ALTER TABLE campaigns ADD COLUMN phones TEXT NOT NULL DEFAULT '[]';
ALTER TABLE campaigns ADD COLUMN pending INTEGER NOT NULL DEFAULT 0;
ALTER TABLE campaigns ADD COLUMN cancelled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE campaigns ADD COLUMN failed INTEGER NOT NULL DEFAULT 0;
