ALTER TABLE businesses ADD COLUMN contact_phone TEXT NOT NULL DEFAULT '';
ALTER TABLE businesses ADD COLUMN sender_name TEXT NOT NULL DEFAULT '';
ALTER TABLE businesses ADD COLUMN optout_line INTEGER NOT NULL DEFAULT 1;
ALTER TABLE contacts ADD COLUMN optout INTEGER NOT NULL DEFAULT 0;
